# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
#  release    pup   ruby      eol
# PE 2016.4   4.7   2.1.9  TBD (LTS)
# PE 2016.5   4.8   2.1.9  2017-10-31
# SIMP6.0.0   4.8   2.1.9  TBD
# PE 2017.1   4.9   2.1.9  2017-10-31
# PE 2017.2   4.10  2.1.9  TBD
---
language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake test
notifications:
  email: false
rvm:
  - 2.1.9
env:
  global:
    - STRICT_VARIABLES=yes
  matrix:
    - PUPPET_VERSION="~> 4.8.2" FORGE_PUBLISH=true
    - PUPPET_VERSION="~> 4.10.0"
    - PUPPET_VERSION="~> 4.9.2"
    - PUPPET_VERSION="~> 4.7.0"
matrix:
  fast_finish: true

before_deploy:
  - 'bundle exec rake metadata_lint'
  - "export PUPMOD_METADATA_VERSION=`ruby -r json -e \"puts JSON.parse(File.read('metadata.json')).fetch('version')\"`"
  - '[[ $TRAVIS_TAG =~ ^${PUPMOD_METADATA_VERSION}$ ]]'
deploy:
  - provider: puppetforge
    user: simp
    password:
        secure: "vboFVqPZoeV4nxdXntwf9OgiNUIBHvgJoWlnycL8IpBdoohX3EUmq9/S3dPX8e9GyG2Kvq3obqUqlYS3IrZ2r0pmB+JGhK7sadixyPa5D1C+8GS0e/qgTHZSL7Rn5OtcHFf7qOq5AXFAbxbLPGlxlKLajXtN3c1nFSXZgCE7IM13haUb8DIBxBzHTVc6+peadrGxcgjTishhJVeRllfbfYp9+DLh5VuN5xL0clUDYLRvMSXQXFPXmttR6OU3lIy6sR4t51SGkBfVtdXDppjHufOn6DsCGG64XFNvGFF03Mij9yU26mO4wY1ku8UgA6gNZeJ3jlEz35yKEiHL9nWXcFq15Jnot9AQ+L2SqtpZZU9nbEZ4H2Bx87VMAv9wKEMtVztrzYmUoZ/v/GGq/AIxsC12OG0tEekA5uh5YB4udkaPgRxJNwCZxqe86vC/dGXUBukfhVdqZemEcubLa8xopyOKBAF+jz/qfpspo4pTYvWB1/TSSuAmcUu7fzv8aqP/x0EQ9KycWzkyi9BhOS2jgNTIufRSTFgMqKt5I+s2tfI5Qgi9CThmItn4kPeFlKWCKupugY0MkIB9RNV6yB2VlvN10Q7hHr33A+SAez0TIftZuR4Q3jgHT2OI5AAdJAiV7FRYaf0WFBAUawP1ruLa9XMkRC5ZfJcSrZPwe2Rkg8A="
    on:
      tags: true
      rvm: 2.1.9
      condition: '$FORGE_PUBLISH = true'
  - provider: releases
    api_key:
        secure: "YQcvfth/9gmKSb6MBz6dc9Lu/BttX9bmPtnjU+UOuaBIjkkkrzPxUrupWlmFrtVz0KxKi12oUl+2f4EkRcnenvRTwbIreZQ1TynaOt8t7GOh8RhF4/qikAYAy4hyuy4k7foKKsqyJEfKvCG9ChDw2kS2FA6Horsg0GHGpxp93sG0mzJE/g1pCZYIzJCQvKcNZud+ALpg0mR85Z1eaEVGfb6xRvjljJITznh+NlvtsnYwTGwbNnMXbjbBBpgv3oyP63RL0R30pjrNkVgtACJAhiQll0Km7rAxPxtys7WqlysodPGs1VF/mP/PJWWnJFD9AN2VdnlXYDArEywpD09EbAyKihiB1JqbbIJrRwv6919LPa4C7Q9pKgh4RIx6XrGy+jqFAdIAqzyd5HJ580Pl9E2bHJCl3EJKL5MD6UAmPhRXC2TNPHT749avvqoSPBCAr3bYp34cWIuUicoBXwaCLDey1IAPsnMkfVF3V8LFSh+p1WDHm6hSEFIctcefKgQaD28XP38yvQ6wxneFT8GuNALADSXOCi89bDy5OBXfEPywP8mJR3TbvE7FLmlInOyr9gaJLwEdKjZ+FfV/GOXxV/UvoIYeP03w8/BT55FWAX4v+O+esYpE0qi2YFk9BJHxRi8l7pljCsmz+omyxXc8N2QN9QC6lOLRT4pc56yvnic="
    skip_cleanup: true
    on:
      tags: true
      condition: '$FORGE_PUBLISH = true'
